steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >
        gcloud secrets versions access latest --secret=staging-env
        --format='get(payload.data)' --project=${PROJECT_ID} > .env
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >
        gcloud secrets versions access latest --secret=gcs-credentials
        --format='get(payload.data)' --project=${PROJECT_ID} >
        kat-23-66e73f4885b6.json
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/${PROJECT_ID}/dikpus-info:staging'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/${PROJECT_ID}/dikpus-info:staging'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - instances
      - update-container
      - kat-staging
      - '--container-image'
      - 'gcr.io/${PROJECT_ID}/dikpus-info:staging'
options:
  logging: CLOUD_LOGGING_ONLY
