version: "3.9"
services:
  database:
    container_name: database
    image: postgres:15.0-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - 5432:5432

  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    depends_on:
      - database
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - SESSION_MAXAGE=${SESSION_MAXAGE}
      - S_MAXAGE=${S_MAXAGE}
      - STALE_WHILE_REVALIDATE=${STALE_WHILE_REVALIDATE}
      - SAMPLER_RATIO=${SAMPLER_RATIO}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - BUCKET_NAME=${BUCKET_NAME}
      - URL_EXPIRATION_TIME=${URL_EXPIRATION_TIME}
      - BUCKET_CORS_EXPIRATION_TIME=${BUCKET_CORS_EXPIRATION_TIME}

volumes:
  database:
